spring.application.name=training-management-system

spring.datasource.url=jdbc:postgresql://ep-divine-math-atust0le-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Taxq58nBILdD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
